name: glucowar
description: A command line utility for glucowar
version: 0.1.0
# homepage: ?

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: any
  dart_console: any
  path: ^1.8.0
  realm_dart: any
  qr: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
